name: Unit Testing


on: [push]

jobs:
  ut_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pylint

      - name: Game logic tests
        run: |
          cd src
          pytest --cov --cov-fail-under=100

      - name: Pylint tests
        run: |
          pylint --fail-under=10 block_game.py
          cd src
          pylint --fail-under=10 game_state.py
          pylint --fail-under=10 obstacle_classes.py
          pylint --fail-under=10 test_game_logic.py